name: ADF Deployment
on: workflow_dispatch
permissions:
      id-token: write
      contents: read
jobs:
  adf-sg-prd:
    runs-on: ubuntu-latest
    steps:
      # Checkout adf_publish branch
      - uses: actions/checkout@v3
        with:
          ref: adf_publish
          
      # Login to Azure Subscription using Managed Identity
      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      # - name: Deploy Hub
      #   uses: azure/powershell@v1
      #   with:
      #     inlineScript: ./PrePostDeploymentScript.Ver2.ps1 -armTemplate "source-adf/ARMTemplateForFactory.json" -ArmTemplateParameters "source-adf/ARMTemplateParametersForFactory.json"  -ResourceGroupName "demo" -DataFactoryName "destination-adf" -predeployment $true -deleteDeployment $false
      #     azPSVersion: "latest"

      # Deploy using ARM Templates
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: demo
          template: source-adf/ARMTemplateForFactory.json
          # Overriding parameters based on the environment
          parameters: 'factoryName=destination-adf'

      - name: Deploy Hub
        uses: azure/powershell@v1
        with:
          inlineScript: ./PrePostDeploymentScript.ps1 -armTemplate "source-adf/ARMTemplateForFactory.json" -ResourceGroupName "demo" -DataFactoryName "destination-adf" -predeployment $false -deleteDeployment $true
          azPSVersion: "latest"  
          
